### ISSUE TITLE
Adhere to Otel semantic conventions

### ISSUE THREAD

**Issue by bryannaegele** [ricardoccpaiva/opentelemetry_tesla#1]
Nice to see this getting started! I poked around the code and noticed there's a lot of deviation from the required semantic conventions for http. It's important to adhere to the spec as much as possible and not add any extra attributes than what are outlined. If the user wants to add more, they should probably be advised to do so through additional custom middleware.

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md

Feel free to drop any questions or ask for reviews in the opentelemetry channel on the Elixir slack!

**Comment by ricardoccpaiva** [comment]
> Nice to see this getting started! I poked around the code and noticed there's a lot of deviation from the required semantic conventions for http. It's important to adhere to the spec as much as possible and not add any extra attributes than what are outlined. If the user wants to add more, they should probably be advised to do so through additional custom middleware.
> 
> https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md
> 
> Feel free to drop any questions or ask for reviews in the opentelemetry channel on the Elixir slack!

Hi Bryan ! thanks for your comment on this project.
I'll take some time to fix those issues and then I'll drop a message on Elixir slack.
See you soon.

**Comment by ricardoccpaiva** [comment]
Work in progress on this subject: #2

**Comment by ricardoccpaiva** [comment]
can we close this @bryannaegele ?

**Comment by bryannaegele** [comment]
Yep! I think you nailed it.
