### ISSUE TITLE
Debug statements in the latest (1.3.2-rc.3) version

### ISSUE THREAD

**Issue by indrekj** [ricardoccpaiva/opentelemetry_tesla#15]
The latest release has this code snippet:

```
        {:error, _} = e ->
          e |> IO.inspect(label: "------>")
          IO.puts("---------> HAAAAAAAAAAA")
          # TODO: update span's status to with appropriate error code and message
          e
```

The code on the master branch doesn't seem to have it so probably something got messed up when the package was published. Could you please do a re-release?

**Comment by ricardoccpaiva** [comment]
sorry for that @indrekj , in fact some local changes for testing messed up the package publishing process, `1.3.2-rc.4` is out now. thanks for reporting.
