### ISSUE TITLE
Submit to OpenTelemetry Contrib

### ISSUE THREAD

**Issue by tsloughter** [ricardoccpaiva/opentelemetry_tesla#16]
I forget if we discussed this on Slack and since there is no history I'm just opening this here.

Are you able to submit this app to https://github.com/open-telemetry/opentelemetry-erlang-contrib

**Comment by ricardoccpaiva** [comment]
> 

Hi @tsloughter 👋 
Yes, I think we discussed it at some point in time 😅 
I'll try to do that ASAP.
Thanks for dropping a message.

**Comment by ricardoccpaiva** [comment]
@tsloughter what do you think of getting this merged before? :point_down: 
https://github.com/ricardoccpaiva/opentelemetry_tesla/pull/17

**Comment by fcevado** [comment]
is this moving to https://github.com/open-telemetry/opentelemetry-erlang-contrib ?
I was about to open a issue/pr for adding an option to the middleware for custom span names.
i can do that in the contrib repo.

**Comment by tsloughter** [comment]
@fcevado that is still the plan.

**Comment by ricardoccpaiva** [comment]
I have a day off tomorrow and I'll take care of that!

**Comment by ricardoccpaiva** [comment]
@tsloughter @fcevado the PR is now open :point_down: 
https://github.com/open-telemetry/opentelemetry-erlang-contrib/pull/90

**Comment by ricardoccpaiva** [comment]
task completed ✅
